#!/bin/bash
set -e
cd $(dirname "$0")/..

rm -f core
ulimit -c unlimited
if [ ! -e "build/Makefile" ];then
    node-gyp configure
fi
make -w -C build -s
echo "test: Entering directory '$(pwd)'"

export TZ=UTC

exec node_modules/.bin/mocha -C -R dot "$@"
