#!/bin/sh
set -e
cd $(dirname "$0")/..

echo "test: Entering directory '$(pwd)'"

rm -f core
ulimit -c unlimited || echo "no core dumping :("
if [ ! -e "build/Makefile" ];then
    node-gyp configure
fi

node-gyp build

export TZ=UTC

cd test
echo "test: Entering directory '$(pwd)'"

exec ../node_modules/.bin/mocha -C -R dot .
